### PR TITLE
fix multibyte characters in two chunks

### LINKED ISSUE #25: Multibyte characters spanning more than one chunk.
I wrote a failing test showing this - based on the feature branch for PR #24. It can be seen here: https://github.com/gustavnikolaj/express-interceptor/commit/db241a745dfe50e2234fc73153b519ac25172e1d

The output is as follows:

```
  1) Multibyte character ☺ smiley face:
     Error: 
expected express app to yield exchange { request: 'GET /smiley', response: { body: '☺' } }

GET /smiley HTTP/1.1

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/plain; charset=utf-8
Date: Fri, 29 May 2015 13:20:30 GMT
Connection: keep-alive
Transfer-Encoding: chunked

-���
+☺
```

This is due to the convertion to utf-8 done on each call to `res.write`. https://github.com/axiomzen/express-interceptor/blob/master/index.js#L35

I can submit a PR fixing this.

### PR DESCRIPTION
**Pull request by gustavnikolaj**
Fixes #25 :-)

### CODE REVIEW

**Comment by p1nox** [comment]
LGTM, thanks @gustavnikolaj :+1:

**Comment by gustavnikolaj** [comment]
thanks :) :+1:

**Comment by gustavnikolaj** [comment]
When will this be released? :-)

**Comment by p1nox** [comment]
I thought this was already done, taking care of it!

**Comment by gustavnikolaj** [comment]
Thanks! I made an issue just a few seconds ago before seeing your response. https://github.com/axiomzen/express-interceptor/issues/29

**Pull request merged**
