### PR TITLE
Closed issue #35 fixed node 4 incopability

### PR DESCRIPTION
**Pull request by nikolaybaldzhiev**
Removed buffer.concat

### CODE REVIEW

**Comment by p1nox** [comment]
Thanks for your support!

There is a failing test, can you check that case @nikolaybaldzhiev ? cc @algebris

```
1) Multibyte character ☺ smiley face:
     UnexpectedError: 
expected express app to yield exchange { request: 'GET /smiley', response: { body: '☺' } }
```

**Comment by gustavnikolaj** [comment]
The proper fix for this, is not changing `Buffer.concat` to something else.

In pre-iojs versions of node, `Buffer.concat` would, when called with an array with exactly one item, just return that one item. So `Buffer.concat(['string'])` would return `'string'`. Given that `String.prototype.toString` is an identity function, this would work. That behaviour changed somewhere after v0.12.

So the proper fix would be changing the following lines, to ensure that whatever you put into the string is a buffer.

https://github.com/axiomzen/express-interceptor/blob/master/index.js#L34-L36

**Comment by gustavnikolaj** [comment]
An example of the proper fix can be seen here, in a related module: https://github.com/gustavnikolaj/hijackresponse/blob/ae55e2acb55535d0c8d8908e3f678ddae97f62f6/lib/hijackResponse.js#L28-L33

**Comment by gustavnikolaj** [comment]
I sent a pull requests, with tests documenting the problem, which is referenced above.

**Comment by p1nox** [comment]
Closing in favor of https://github.com/axiomzen/express-interceptor/pull/37 , thanks guys @gustavnikolaj @nikolaybaldzhiev @algebris

**Pull request closed without merging**
