### PR TITLE
Remove .toString('utf-8') for intercepting binary responses

### PR DESCRIPTION
**Pull request by fuminchao**
Think if we need to add watermark on the outgoing images.
I think it is better to remove toString, in that the interceptors can decide how to decode the origin response body.
Currently, it can only intercept text body, right ?

### CODE REVIEW

**Comment by abualiNT** [comment]
any plans to merge this ?

**Comment by fuminchao** [comment]
@abualiNT 
The owner seems inactive for a while.

**Comment by flockonus** [comment]
Hi @fuminchao , sorry for the delay to get back about your PR.

Unfortunately the only projects we have using interceptor now don't have use case to intercept binary, and we'd rather not push any breaking changes.

If you'd like to publish your fork as an npm packaged we are happy to link your fork with the respective use case in the Similar to section of the README - let us know.

**Comment by fuminchao** [comment]
I will open another PR for compatible change

**Pull request closed without merging**
